"""将 graphify 社区标签从英文翻译为中文"""
import json

translation = {
    "Tailwind CSS Bundle": "Tailwind CSS 样式包",
    "Dashboard State Management": "面板状态管理",
    "Chart Series Properties": "图表序列属性",
    "Lightweight Charts Library": "轻量图表库",
    "Backtest Report Adapter": "回测报告适配器",
    "Report Adapter Functions": "报告适配函数",
    "Chart Drawing Instance": "图表绘制实例",
    "Backend API Routes": "后端API路由",
    "Chart Range Utilities": "图表区间工具",
    "Strategy LLM Researcher": "策略LLM研究器",
    "Chart Object Internals": "图表对象内部",
    "Chart Element Properties": "图表元素属性",
    "Chart Series Management": "图表序列管理",
    "Chart Coordinate Properties": "图表坐标属性",
    "Chart Coordinate Options": "图表坐标选项",
    "Gene Strategy Adapter": "基因策略适配器",
    "Price Scale Utilities": "价格刻度工具",
    "Chart Data Panes": "图表数据面板",
    "Frontend Config Actions": "前端配置动作",
    "Backtest Data Stores": "回测数据存储",
    "CSS Utility Functions": "CSS工具函数",
    "Batch CSV Task UI": "批量CSV任务界面",
    "Live Trading Cabinet": "实盘交易柜",
    "DOM Manipulation Utilities": "DOM操作工具",
    "Live & Backtest APIs": "实盘与回测API",
    "Desktop App Launcher": "桌面应用启动器",
    "Evolution UI State": "进化界面状态",
    "Chart Series Markers": "图表序列标记",
    "Broker Terminal Gateway": "券商终端网关",
    "Strategy Library Manager": "策略库管理器",
    "Chart Drawing Utils": "图表绘制工具",
    "AI Report Review API": "AI报告审阅API",
    "CSS Parsing Utilities": "CSS解析工具",
    "Tushare Data Provider": "Tushare数据源",
    "Consistency Diff Comparator": "一致性差异比较器",
    "K-line Data Validation": "K线数据校验",
    "LLM & History Sync API": "LLM与历史同步API",
    "Strategy DB Operations": "策略数据库操作",
    "Strategy Manager API": "策略管理API",
    "Base Strategy Class": "策略基类",
    "Live Account Metrics UI": "实盘账户指标界面",
    "Cached Data Provider": "缓存数据源",
    "Ministry-Style Framework": "三省六部框架",
    "Strategy Selection UI": "策略选择界面",
    "Batch Combination UI": "批量组合界面",
    "Chart Item Converter": "图表项转换器",
    "DuckDB History Sync": "DuckDB历史同步",
    "Fundamental Data Adapter": "基本面数据适配",
    "Signal Risk Control": "信号风控",
    "Ollama LLM Adapter": "Ollama大模型适配",
    "CSS Utility Names": "CSS工具命名",
    "Webhook Notifier": "Webhook通知器",
    "Genetic Algorithm Engine": "遗传算法引擎",
    "DuckDB Sync Diagnosis": "DuckDB同步诊断",
    "Error Handling Utilities": "错误处理工具",
    "Evolution Family API": "进化族谱API",
    "Screener Filter Options": "筛选器过滤选项",
    "Strategy Exit Signals": "策略退出信号",
    "CSS Manipulation Functions": "CSS操作函数",
    "Concurrency Manager": "并发管理器",
    "Signal Generation & Validation": "信号生成与校验",
    "Batch Backtest Runner": "批量回测执行器",
    "Backtest Adapter": "回测适配器",
    "Evolution Platform UI": "进化平台界面",
    "Evolution Checkpointing": "进化检查点",
    "Abstract Data Provider": "抽象数据源",
    "Data Factory & Providers": "数据工厂与数据源",
    "DuckDB Provider": "DuckDB数据源",
    "Config & Connectivity APIs": "配置与连通性API",
    "TDX Formula APIs": "通达信公式API",
    "Runtime Provider Selection": "运行时数据源选择",
    "JQData Provider": "JQData数据源",
    "Webhook & Batch Runner": "Webhook与批量执行",
    "Config Loader & AI Analysis": "配置加载与AI分析",
    "Monitoring Dashboard": "监控面板",
    "Chart Drawing Methods": "图表绘制方法",
    "Variant Offset Calculations": "变体偏移计算",
    "Backtest Cabinet": "回测柜",
    "NL Screener Skill": "自然语言筛选技能",
    "Chart Format Utilities": "图表格式工具",
    "Live Snapshot Collector": "实盘快照采集器",
    "Chart Axis Properties": "图表坐标轴属性",
    "TDX Broker Terminal API": "通达信券商终端API",
    "Backtest Runner & Reports": "回测执行与报告",
    "Strategy Intent Parser": "策略意图解析器",
    "LLM Gateway Adapter": "LLM网关适配器",
    "Screener Demo Strategy": "筛选演示策略",
    "Strategy Critic": "策略评审器",
    "Documentation & Guides": "文档与指南",
    "Fund Curve UI": "资金曲线界面",
    "Task Generation & Coverage": "任务生成与覆盖",
    "K-line Chart Thumbnails": "K线缩略图",
    "Strategy Template Library": "策略模板库",
    "Right Panel UI State": "右侧面板状态",
    "DuckDB Data Writer": "DuckDB数据写入",
    "Backtest Report Scoring": "回测报告评分",
    "Responsive Breakpoints CSS": "响应式断点CSS",
    "TDX Formula Compiler": "通达信公式编译器",
    "CSS Helper Functions": "CSS辅助函数",
    "Config Center & Cache": "配置中心与缓存",
    "Data Providers & Libraries": "数据源与库",
    "Protobuf Field Definitions": "Protobuf字段定义",
    "Strategy Loader": "策略加载器",
    "Trade Execution Engine": "交易执行引擎",
    "Task File Management": "任务文件管理",
    "Replay Run Management": "回放运行管理",
    "Batch Task API": "批量任务API",
    "CSS Parser Errors": "CSS解析错误",
    "AI Execution Rules Adapter": "AI执行规则适配",
    "Order Matching & Stop Orders": "订单撮合与止损",
    "Fund Pool Adjustment": "资金池调整",
    "Pattern Picker UI": "形态选择界面",
    "Disable Field Logic": "字段禁用逻辑",
    "Database Schema Management": "数据库模式管理",
    "Dependency Bootstrap": "依赖自举安装",
    "Pane View Management": "面板视图管理",
    "Marker Management": "标记管理",
    "System Startup Scripts": "系统启动脚本",
    "Consistency Compare API": "一致性比较API",
    "Mock Data Generator": "模拟数据生成器",
    "Genetic Algorithm Config": "遗传算法配置",
    "Desktop Build Script": "桌面构建脚本",
    "Minute Data Cache": "分钟数据缓存",
    "Stock Manager": "股票管理器",
    "Regex Properties": "正则属性",
    "User Strategy Template": "用户策略模板",
    "PowerShell Startup Script": "PowerShell启动脚本",
    "Evolution Profile API": "进化配置API",
    "Screener Data Sources": "筛选数据源",
    "Dual MA Strategy": "双均线策略",
    "Deploy & Start Script": "部署启动脚本",
    "Custom Strategy Instantiation": "自定义策略实例化",
    "TDX Provider Test": "通达信数据源测试",
    "TDX Formula Batch Adapter": "通达信公式批量适配",
    "Backtest Chart & K-line": "回测图表与K线",
    "History Sync Checkpoint Toggle": "历史同步检查点切换",
    "Real-time Quote API": "实时行情API",
    "Data Service Diagram": "数据服务图",
    "QR Code Image": "二维码图片",
    "Coupon Image": "优惠券图片",
    "Silicon Flow Code": "硅基流代码",
    "Strategy Evolution Board": "策略进化看板",
    "Video Update Screenshot": "视频更新截图",
    "Backtest K-line Display": "回测K线展示",
    "Backtest Mode": "回测模式",
    "Backtest Report": "回测报告",
    "Batch Backtest Dashboard": "批量回测看板",
    "Live Mode": "实盘模式",
    "Live Signal Push": "实盘信号推送",
    "Three Departments Diagram": "三省六部体系图",
    "Config Center Draft Actions": "配置中心草稿动作",
    "Constants Module": "常量模块",
    "Pane View Attach/Detach": "面板视图挂载/卸载",
    "Arbitrary Property": "任意属性",
    "Time Series Conditions": "时序条件",
}

# 从备份 graph.json 提取英文标签
with open("graphify-out/2026-06-27/graph.json", "r", encoding="utf-8") as f:
    data = json.load(f)

en_labels = {}
for node in data.get("nodes", []):
    cid = node.get("community")
    cname = node.get("community_name", "")
    if cid is not None and cname and not cname.startswith("Community "):
        en_labels[str(cid)] = cname

# 翻译
zh_labels = {}
untranslated = []
for cid, en_name in en_labels.items():
    if en_name in translation:
        zh_labels[cid] = translation[en_name]
    else:
        zh_labels[cid] = en_name
        untranslated.append(en_name)

# 写入 .graphify_labels.json
with open("graphify-out/.graphify_labels.json", "w", encoding="utf-8") as f:
    json.dump(zh_labels, f, ensure_ascii=False, indent=2)

print(f"已翻译 {len(zh_labels)} 个社区标签")
if untranslated:
    print(f"未翻译（保留原名）: {untranslated}")
